services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: askarkg12/audio-frontend:latest
    labels:
      - "traefik.enable=true"
      - "${TRAEFIK_LABEL1}"
      - "${TRAEFIK_LABEL2}"
      - "${TRAEFIK_LABEL3}"
    networks:
      - traefik_default
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: askarkg12/audio-backend:latest

networks:
  traefik_default:
    external: true
